
use IBWT


-- ***** CONTRAINTES D'UNICITE*************************************************************

-- EVITER PLUSIEURS LIGNES DE COMMANDE AVEC 
-- LE MEME ARTICLES
ALTER TABLE LigneDeCommande
ADD CONSTRAINT unLigIdComId


UNIQUE (ligId,comId)


--EVITER LE VERSEMENT DE PLUSIEURS REGLEMENTS
--A LA MEME DATE, AU MEME SERVICE BANCAIRE
ALTER TABLE Paiement
ADD CONSTRAINT unPaiNumPaiDateSerIdComId

UNIQUE (paiNum,paiDate,serId,comId)


-- EVITER PLUSIEURS LIVRAISONS DE 
-- LA MEME COMMANDE, AVEC DES TRANSPORTEURS DIFFERENTS  
ALTER TABLE Expedition
ADD CONSTRAINT unExpNumSuiviComIdTraId

UNIQUE (expNumSuivi,comId,traId)

-- EVITER PLUSIEURS COMMENTAIRES DU 
-- MEME CLIENT, POUR LA MEME OEUVRE  
ALTER TABLE Commentaire
ADD CONSTRAINT unCmtIdOeuIsbnCliId

UNIQUE (cmtId,oeuIsbn,cliId)


-- *****CONTRAINTES DE CHECK***************************************************************

-- VERIFIER QUE LA DATE DE LIVRAISON EST POSTERIEURE
-- A CELLE D'ENVOI
ALTER TABLE Expedition
ADD CONSTRAINT chExpDateLivraisonExpDateEnvoi
CHECK (expDateLivraison >= expDateEnvoi)

-- VERIFIER QUE LA DATE DE SORTIE CLIENT EST POSTERIEURE
-- A CELLE DE ENTREE
ALTER TABLE Client
ADD CONSTRAINT chCliDateSortieCliDateEntree
CHECK (cliDateSortie >= cliDateEntree)

-- VERIFIER QUE LA DATE DE SORTIE UTILISATEUR EST POSTERIEURE
-- A CELLE DE ENTREE
ALTER TABLE Utilisateur
ADD CONSTRAINT chUtiDateSortieUtiDateEntree
CHECK (utiDateSortie >= utiDateEntree)

-- VERIFIER QUE LA DATE DE SORTIE EVENEMENT EST POSTERIEURE
-- A CELLE DE ENTREE
ALTER TABLE Evenement
ADD CONSTRAINT chEveDateFinEveDateDebut
CHECK (eveDateFin >= eveDateDebut)

-- VERIFIER QUE LE STOCK DE L'OEUVRE NE SOIT PAS INFERIEUR
-- A '0'
ALTER TABLE Oeuvre
ADD CONSTRAINT chOeuStock
CHECK (oeuStock >= 0)

-- VERIFIER QUE LE PRIX OEUVRE NE SOIT PAS INFERIEUR
-- A '0'
ALTER TABLE Oeuvre
ADD CONSTRAINT chOeuPrix
CHECK (oeuPrix >= 0)

-- VERIFIER QUE LE PRIX LIGNE DE COMMANDE NE SOIT PAS INFERIEUR
-- A '0'
ALTER TABLE LigneDeCommande
ADD CONSTRAINT chLigPrix
CHECK (ligPrix >= 0)



-- *****CONTRAINTES DE DEFAULT*************************************************************

-- INSERER LA VALEUR '1' DANS LA QUANTITE COMMANDE 
-- DANS LA TABLE LIGNE DE COMMANDE PAR DEFAUT
ALTER TABLE LigneDeCommande
ADD CONSTRAINT dfLigQteCommandee
DEFAULT 1 FOR ligQteCommandee

-- INSERER LA VALEUR '5.50' DANS LE TAUX TVA
-- DANS LA TABLE TVA PAR DEFAUT
ALTER TABLE TVA
ADD CONSTRAINT dfTvaTaux
DEFAULT 5.5 FOR tvaTaux

-- INSERER LA VALEUR '5.00' DANS LES FRAIS DE PORT
-- DANS LA TABLE TRANSPORTEUR PAR DEFAUT
ALTER TABLE Transporteur
ADD CONSTRAINT dfTraFraisDePort
DEFAULT 5.00 FOR traFraisDePort

--INSERER LA VALEUR 'FRANCE' DANS LE PAYS
--DE L'ADRESSE PAR DEFAUT
ALTER TABLE Adresse
ADD CONSTRAINT dfAdrPays
DEFAULT 'FRANCE' FOR adrPays

-- INSERER LA VALEUR 'Resume a venir' DANS LE RESUME DE L'OEUVRE
ALTER TABLE Oeuvre
ADD CONSTRAINT dfOeuResume

DEFAULT 'Resume a venir' FOR oeuResume

-- INSERER LA VALEUR '10' (DISPONIBLE) DANS LE STATUT DE L'OEUVRE
-- //SI LE STOCK DE L'OEUVRE EST SUPERIEUR'0'(>>PAS POSSIBLE?)// 
ALTER TABLE Oeuvre
ADD CONSTRAINT dfOeuStatut

DEFAULT '10' FOR oeuStatut

-- INSERER LA VALEUR '20' (EN COUR DE VALIDATION) DANS LE STATUT DU COMMENTAIRE
ALTER TABLE Commentaire
ADD CONSTRAINT dfCmtStatut

DEFAULT '20' FOR cmtStatut

-- INSERER LA VALEUR '30' (EN COUR DE PREPARATION) DANS LE STATUT DU COMMANDE
ALTER TABLE Commande
ADD CONSTRAINT dfComStatut

DEFAULT '30' FOR comStatut

-- INSERER LA VALEUR '42' (VALIDE) DANS LE STATUT DU ADRESSE
ALTER TABLE Adresse
ADD CONSTRAINT dfAdrStatut

DEFAULT '42' FOR adrStatut

---- INSERER LA DATE DU JOUR DANS LA DATE DE PAIEMENT
ALTER TABLE Paiement
ADD CONSTRAINT dfPaiDate

DEFAULT SYSDATETIME() FOR paiDate

---- INSERER LA DATE DU JOUR DANS LA DATE D'ENTREE PAR DEFAUT POUR LE CLIENT
ALTER TABLE Client
ADD CONSTRAINT dfCliDateEntree

DEFAULT GETDATE() FOR cliDateEntree

---- INSERER LA DATE DU JOUR DANS LA DATE D'ENTREE PAR DEFAUT POUR L'UTILISATEUR
ALTER TABLE Utilisateur
ADD CONSTRAINT dfUtiDateEntree

DEFAULT GETDATE() FOR utiDateEntree


-------------------------------------------------------------------------------------------
-- FAIRE EN TRIGGERS **********************************************************************
-------------------------------------------------------------------------------------------

---- INSERER LA VALEUR utiPrenom+'.'+utiNom'@IBTW.fr' DANS L'EMAIL UTILISATEUR
--ALTER TABLE Utilisateur
--ADD CONSTRAINT dfUtiEmail

----DEFAULT (utiPrenom+'.'+utiNom+'@IBWT.fr') FOR utiEmail